version: "3"
services:
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  template:
    driver: local

networks:
  template:
    external: true
